### ISSUE TITLE
Branch Issues

### ISSUE THREAD

**Issue by chedburgh** [tango-controls-hdbpp/libhdbpp-timescale#13]
The merge/revert of the enum support, which branched from the project-build2 branch has caused problems trying to roll all the project-build2 changes in (many are missing, since they were previously reverted).

This needs fixing and a PR raising for project-build2.

**Comment by dlacoste-esrf** [comment]
Something wrong definitely happened here. I think we will merge all the branches and tag as v2.0.0 if all goes well.

**Comment by chedburgh** [comment]
No, that is dangerous. You reverted enum support for some reason? 

I propose we roll in the project-build2 changes (v1.0.0), then enum support (v1.1.0). That way users can choose where they are on the path.

I'll separate out the branches later.

**Comment by dlacoste-esrf** [comment]
I reverted it cause I merged it by mistake, it wasn't intended (nor reviewed).

Ok for releasing multiple versions (project-build2 should be 2.0.0 to match libhdbpp though…), but I think here we will directly roll the batch insert and enum support to production, so intermediate version won't have any time running in production.

**Comment by chedburgh** [comment]
The use of the intermediate versions is to drop back if there is a problem with the current version. Batch + Enum have not had much testing yet?

If you really want to just merge everything and hope it works, go for it, but I would really suggest a staggered approach (by the book release procedure), to give rollback positions, smaller diffs and easier to debug releases.

**Comment by dlacoste-esrf** [comment]
I agree with you, let's do it step by step.

But since updating software here can be tricky, the intermediate version will not be used into production.

**Comment by chedburgh** [comment]
I am looking at the best way to create a new clean master branch. From that we will raise a PR for the project-build2 branch.

**Comment by dlacoste-esrf** [comment]
just merge project-build2 and make it the master. the latest tag should be ok, before this mess.

**Comment by chedburgh** [comment]
It does not work. The revert in master removed most of the changesets project-build2 requires (for an example, merge master into project-build2 locally). This was then reverted. The revert is not a rollback, it is another commit on the master, hence the problem.

I can pick this apart later, probably with some new branches.

**Comment by dlacoste-esrf** [comment]
I am starting to realize as well. Sorry for the mess, this revert did not go as I planned.
is it ok to drop v1.0.0 and directly jump to 2.0.0 to follow libhdbpp ?

**Comment by chedburgh** [comment]
Its ok, reverts result is not obvious on first use. Version number can be anything, but I suggest its incremented when we merge project-build2 in.

**Comment by dlacoste-esrf** [comment]
I created a new branch, project-build3, that should fix our issues.
I used it as well to push some change on how to use libhdbpp (which is now only needed for a header), any comments on this would be welcome.
thx

**Comment by gscalam** [comment]
Shouldn't fetch "v2.0.0" and not "project-build" as GIT_TAG when looking for libhdbpp headers ?

**Comment by dlacoste-esrf** [comment]
I did some more modifications on libhdbpp actually… They are in the project-build branch so far. You can have a look, I removed HdbClient from the public headers space and did some modification in the cmake file to properly (as far as I can say at least) export this project. It then can be found with cmake's find_package, which is quite nice.
