### ISSUE TITLE
AttributeName::operator= compilation warning

### ISSUE THREAD

**Issue by bourtemb** [tango-controls-hdbpp/libhdbpp-timescale#3]
When compiling libhdbpp-timescale on Debian Buster, gcc 8.3 is reporting the following compilation warning:

```
libhdbpp-timescale/src/AttributeName.cpp:293.1: warning: no return statement in function returning non-void [-Wreturn-type]
}
^
```

This method should return `*this` to be able to chain this operator.

**Comment by chedburgh** [comment]
Fixed in #5
