### ISSUE TITLE
DbConnection::storeParameterEvent shouls allow empty config parameters in debug mode

### ISSUE THREAD

**Issue by bourtemb** [tango-controls-hdbpp/libhdbpp-timescale#4]
Many assert calls are done at the beginning of DbConnection::storeParameterEvent method:
https://github.com/tango-controls-hdbpp/libhdbpp-timescale/blob/1ac5bc999c0862ff7f7ca3b099d70b71595ba2d5/src/DbConnection.cpp#L263-L271
This will cause a crash of the hdbpp-es if it subscribes to attribute configuration events on attributes having some of their configuration parameters which are empty.
This crash will happen only when using the debug version of the library.

The library shall not crash in this use case.
There is nothing to impose our users to put something in every parameter of an attribute configuration and the HdbEventSubscriber should not have this role. We shouldn't make this assumption that every parameter composing an attribute configuration shall not be empty.

**Comment by chedburgh** [comment]
Fixed in #5
