### ISSUE TITLE
Create log directory if it does not exist yet

### ISSUE THREAD

**Issue by bourtemb** [tango-controls-hdbpp/libhdbpp-timescale#6]
If `log_file_name `LibConfiguration property parameter is set to `/tmp/hdbpp/my_wonderful_log.log` and `/tmp/hdbpp` directory does not exist yet, it would be convenient to try to create this directory instead of logging an error on the console as it is now.

**Comment by dlacoste-esrf** [comment]
pushed latest version of spdlog.
Support for exactly that was added (https://github.com/gabime/spdlog/commit/4a620a2c5e09646cf79cfd9000517ff0d2bb9edd) at some point.
